/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class PuntoFijo */

#ifndef _Included_PuntoFijo
#define _Included_PuntoFijo
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     PuntoFijo
 * Method:    puntoFijo
 * Signature: (DDI)D
 */
JNIEXPORT jdouble JNICALL Java_PuntoFijo_puntoFijo
  (JNIEnv *, jobject, jdouble, jdouble, jint);

#ifdef __cplusplus
}
#endif
#endif
